version: 0.2

#Remember to enable privileged mode on your code build environment https://docs.aws.amazon.com/codebuild/latest/userguide/troubleshooting.html

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 703671917449.dkr.ecr.eu-central-1.amazonaws.com/vulnerableapplicationrepo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t vulnerableapplicationrepo .
      - docker tag vulnerableapplicationrepo:latest 703671917449.dkr.ecr.eu-central-1.amazonaws.com/vulnerableapplicationrepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 703671917449.dkr.ecr.eu-central-1.amazonaws.com/vulnerableapplicationrepo:latest
      # - aws lambda update-function-code --function-name vulnerableapplicationfunction --image-uri 703671917449.dkr.ecr.eu-central-1.amazonaws.com/vulnerableapplicationrepo:latest